language: php

php:
  - 5.6
  - hhvm
  - nightly

before_script: composer install -n

script:
  - phpunit -c ./tests --coverage-clover=coverage.clover
  #- wget https://scrutinizer-ci.com/ocular.phar
  #- php ocular.phar code-coverage:upload --format=php-clover coverage.clover
